GET http://localhost:3000/api/genres

###

GET http://localhost:3000/api/genres/5b8b9c6f9fa17a4ee5bf7389

###

POST http://localhost:3000/api/genres
content-type: application/json

{
  "name":"Crime"
}

###
PUT http://localhost:3000/api/genres/5b8b9c6f9fa17a4ee5bf7389
content-type: application/json

{
  "name":"Action"
}

###
DELETE http://localhost:3000/api/genres/5b8b9c6f9fa17a4ee5bf7389
