GET http://localhost:3000/api/genres

###

GET http://localhost:3000/api/genres/1

###

POST http://localhost:3000/api/genres
content-type: application/json

{
  "name":"Crime"
}

###
PUT http://localhost:3000/api/genres/1
content-type: application/json

{
  "name":"Crime"
}

###
DELETE http://localhost:3000/api/genres/1
